name: Lint

on: push
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"
      - run: yarn install
        working-directory: client
      - run: yarn lint
        working-directory: client
