name: Checker

on: push
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"
      - run: yarn init -y
      - run: yarn add ts-compile-checker
      - run: npx ts-compile-checker

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
