name: Checker

on: push
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"
      - run: yarn install
        working-directory: test
      - run: yarn start --cwd ".."
        working-directory: test
