on: push
name: TS checker
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
        working-directory: ./ts-compile-checker
      - run: yarn start --cwd ".."
        working-directory: ./
